### ISSUE TITLE
My site doesn't match your screenshots

### ISSUE THREAD

**Issue by manishie** [moderatorwes/Zentastic#3]
Thanks for the great work!  I believe I've copied in all the correct assets (including the CSS into the CSS tab and the external css file), but my site (https://zscalertest2.zendesk.com/hc/en-us) doesn't look quite right with the search box and the article listings underneath it.  Thoughts?

Thanks again.

**Comment by moderatorwes** [comment]
Hi Manishie - I took a look at your site and I didn't see any errors when looking in the console.  I believe the issue may be that you need to add another Category or two so that it will populate your accordions.  Under each category apply at least one section and some dummy articles.  Once that is done let me know and I'll take another look for you.

Thanks for using the Zentastic theme.

**Comment by manishie** [comment]
that did it!  thanks again for the great work...

moderatorwes wrote:

**Comment by moderatorwes** [comment]
Glad to hear.

In your Document Head make sure you update to the latest version of Font Awesome and Bootstrap.

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">



<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

**Comment by manishie** [comment]
thanks again!

moderatorwes wrote:
